# Regression Metrics

In [1]:
# import numpy as np 
# import pandas as pd
# import seaborn as sns
# from matplotlib import pyplot as plt 
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeRegressor

# df = sns.load_dataset("tips")
# df.head()

# X = df[['total_bill']]
# y = df['tip']

# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

# model = DecisionTreeRegressor()

# model.fit(X_train, y_train)

# y_pred = model.predict(X_test)

# from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score

# print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
# print(f"Mean Absolute Percentage Error: {mean_absolute_percentage_error(y_test, y_pred)}")
# print(f"Mean Square Error: {mean_squared_error(y_test, y_pred)}")
# print(f"r2 score: {r2_score(y_test, y_pred)}")
# print(f"r2 score: {r2_score(y_test, y_pred)}")

In [2]:
# import numpy as np 
# import pandas as pd
# import seaborn as sns
# from matplotlib import pyplot as plt 
# from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
# from sklearn.model_selection import train_test_split

# df = sns.load_dataset("titanic")

# df.fillna({
#     "age":df.age.mean()
# }, inplace = True)

# model1 = LogisticRegression()
# model2 = DecisionTreeClassifier()

# X_train, X_test, y_train, y_test = train_test_split(df[["age","pclass"]], df["pclass"])

# model1.fit(X_train, y_train)
# model2.fit(X_train, y_train)

# y_pred1 = model1.predict(X_test)
# y_pred2 = model2.predict(X_test)

# from sklearn.metrics import accuracy_score, confusion_matrix

# print(accuracy_score(y_test, y_pred1))
# accuracy_score(y_test, y_pred2)

# pd.DataFrame(confusion_matrix(y_pred1, y_test))
# print(confusion_matrix(y_pred1, y_test))

In [11]:
import numpy as np 
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.model_selection import train_test_split

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [20]:
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [15]:
df.drop('deck', axis=1, inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [22]:
# df["age"].mean()
df["age"] = df["age"].fillna(df["age"].mean())

In [17]:
df.isnull().sum().sort_values(ascending=False)

embark_town    2
embarked       2
sex            0
age            0
survived       0
pclass         0
parch          0
sibsp          0
class          0
fare           0
who            0
adult_male     0
alive          0
alone          0
dtype: int64

In [24]:
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
df["embark_town"].mode()

0    Southampton
Name: embark_town, dtype: object

In [26]:
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64